#!/usr/bin/perl
# Mobiliojo rysio operatoriaus aptikimas pagal telefono numeri.
# 2012 (c) \dev\null (devnull@bsdnet.net)

use strict;
use Cwd qw(abs_path);
sub wrong {
print "Blogai ivestas telefono numeris ? Numeris turetu prasideti 86 arba +370\n";
exit 1;
}
print "Iveskite telefono nr: ";
chomp (my $nr = <>);
# process number
my $basedir = abs_path();
my $numbers = "$basedir/numbers";
wrong unless ("$nr" =~ /^(86|\+370)/);
# check if ^(8|+370)*******$
if ("$nr" =~ /^(8|\+370)........$/) {
print "Tikrinamas numeris...\n";
open(OF, $numbers);
my(@lines) = <OF>;
@lines = sort(@lines);
my ($line);
foreach $line (@lines) {
chomp($line);
my ($regex, $desc) = split("::",$line);
if ("$nr" =~ m/($regex)/) {
print "Ivestas numeris: $nr atitinka tinkla: $desc\n";
exit 0
}
}
print "Atitikmens nerasta, pildykite duomenu baze!\n";
} else { wrong; }
